//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameViewModel
    {
        public int ID { get; set; }
        public string owner { get; set; }
        public string category { get; set; }
        public int numPlayers { get; set; }
        public string name { get; set; }

        public static implicit operator GameViewModel(Game v)
        {
            throw new NotImplementedException();
        }
    }
}
