//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string name { get; set; }
        public int position { get; set; }
        public int gameId { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
